---

resource_types:
- name: ifttt-integration
  type: docker-image
  source:
    repository: switzerswish/ifttt-resource
    tag: latest

resources:
- name: ifttt
  type: ifttt-integration
  source:
    ifttt_key: {{ifttt_api_key}}

jobs:
- name: test-app
  plan:
  - task: say-hello
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      run:
        path: echo
        args:
        - foo
    on_success:
      put: ifttt
      params:
        event_name: "build_passing"
    on_failure:
      put: ifttt
      params:
        event_name: "build_failing"
